[package]
name = "location"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom_locate = "4.0.0"
picktok = { git = "https://github.com/WiZLite/picktok", branch = "main" }
